services:
# ─────────────── Example .NET Service ───────────────
  innovo.catalog.api:
    build:
      context:  ./Services/Catalog/Innovo.Catalog.Api
      dockerfile: Dockerfile
    image: innovo.catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - innovo-net
  innovo.identity.api:
    build:
      context: ./Services/Identity/Innovo.Identity.Api
      dockerfile: Dockerfile
    image: innovo.identity.api
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
volumes:
  es_data:

networks:
  innovo-net:
    driver: bridge
