services:
  innovo.identity.api:
    build:
         context: services/identity/Innovo.Identity.Api
         dockerfile: Dockerfile
    container_name: identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=postgres;Database=identitydb;Username=postgres;Password=postgres
      - ConnectionStrings__SqlServer=Server=sqlserver,1433;Database=identitydb;User Id=sa;Password=Your_password123;
    ports:
      - "5001:80"
  innovo.catalog.api:
    build: 
          context: services/catalog/Innovo.Catalog.Api
          dockerfile: Dockerfile
    container_name: catalog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=postgres;Database=catalogdb;Username=postgres;Password=postgres
      - ConnectionStrings__SqlServer=Server=sqlserver,1433;Database=catalogdb;User Id=sa;Password=Your_password123;
    ports:
      - "5002:80"
  # ─────────────── Databases ───────────────
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
# ─────────────── Volumes ───────────────
volumes:
  postgres-data:
  sqlserver-data:            
